Repository TeamPiickle/client, pull requests merged in 2022-08, with the labels that each got.

#129 Feat/#123 vote
  src/App.tsx
  src/asset/icon/index.ts
  src/components/CardCollection/index.tsx
  src/components/MyPage/MyInfo/index.tsx
  src/components/Vote/AfterVoteList/index.tsx
  src/components/Vote/BeforeVoteList/index.tsx
  src/components/Vote/VoteContent/AfterVoteList/index.tsx
  src/components/Vote/VoteContent/AfterVoteList/style.ts
  src/components/Vote/VoteContent/BeforeVoteList/index.tsx
  src/components/Vote/VoteContent/BeforeVoteList/style.ts
  src/components/Vote/VoteContent/index.tsx
  src/components/common/Header/index.tsx
  src/components/common/LoginModal/index.tsx
  src/components/common/LoginModal/style.ts
  src/components/common/MenuBar/index.tsx
  src/components/common/Modal/style.ts
  src/core/api/vote.ts
  src/core/atom/menuBar.ts
  src/util/hooks/useModal.ts
Labels: Refactor, Fix, 주함

#128 Feat/#126 pc layout
  src/App.tsx
  src/components/CardCollection/CardSlider/style.ts
  src/components/Main/CTABtn/style.ts
  src/style/theme.ts
Labels: Fix, 주함

#132 Feat/#130 pwa
  public/favicon.ico
  public/images/banner.jpg
  public/images/logo.png
  public/index.html
  public/manifest.json
  public/offline.html
  public/pwaServiceWorker.js
  tsconfig.json
Labels: Feature, 주함

#139 [ feat ] GTM 코드 삽입
  public/index.html
Labels: Feature

#140 Feat/#135 joam
  src/components/CardCollectionPage/Tag/index.tsx
  src/components/CardCollectionPage/index.tsx
  src/components/CategoryPage/index.tsx
  src/components/LoginPage/LoginForm/index.tsx
  src/components/LoginPage/hooks/useLoginForm.ts
  src/components/MainPage/BestPiickle/index.tsx
  src/components/MainPage/BestPiickle/style.ts
  src/components/MainPage/MoodPiickle/index.tsx
  src/components/MyPage/MyInfo/index.tsx
  src/components/MyPage/MySetting/index.tsx
  src/components/MyPage/index.tsx
  src/components/VotePage/VoteContent/BeforeVoteList/index.tsx
  src/components/common/Footer/index.tsx
  src/components/common/Header/index.tsx
  src/components/common/Modal/index.tsx
  src/components/common/hooks/useModal.ts
  src/components/common/hooks/useScroll.ts
  src/core/api/bookmark.ts
  src/core/api/main.ts
  src/core/api/vote.ts
  src/types/cardCollection.ts
  src/util/fetchCardCollection.ts
Labels: Refactor, 주함
