Repository TeamPiickle/client, pull requests merged in 2022-09, with the labels that each got.

#147 Feat/#143 email certification
  src/@components/@common/LoginModal/index.tsx
  src/@components/@common/MenuBar/index.tsx
  src/@components/JoinPage/ EmailAuthentication/index.tsx
  src/@components/JoinPage/ EmailAuthentication/style.ts
  src/@components/JoinPage/EmailConfirm/index.tsx
  src/@components/JoinPage/EmailConfirm/style.ts
  src/@components/JoinPage/common/Header/index.tsx
  src/@components/JoinPage/common/Header/style.ts
  src/@components/JoinPage/common/PageProgressBar/index.tsx
  src/@components/JoinPage/common/PageProgressBar/style.ts
  src/@components/LoginPage/LoginForm/index.tsx
  src/@components/MainPage/MoodPiickle/index.tsx
  src/@components/index.ts
  src/Router.tsx
  src/asset/icon/goBackBtn.svg
  src/asset/icon/index.ts
  src/core/join/prevPages.ts
  src/core/join/progressRate.ts
  src/core/routes/path.ts
  src/style/theme.ts
Labels: Feature, 지영

#148 Feat/#145 join agree
  src/@components/JoinPage/JoinAgree/index.tsx
  src/@components/JoinPage/JoinAgree/style.ts
  src/@components/index.ts
  src/Router.tsx
  src/asset/icon/emptyCheckBox.svg
  src/asset/icon/fullCheckBox.svg
  src/asset/icon/index.ts
  src/asset/icon/nextBtn.svg
  src/core/join/prevPages.ts
  src/core/join/progressRate.ts
  src/core/routes/path.ts
  src/style/theme.ts
Labels: Feature, 나연

#155 Feat/#134 routing
  src/@components/@common/hooks/useDebounce.ts
  src/@components/JoinPage/AgreePage/index.tsx
  src/@components/JoinPage/AgreePage/style.ts
  src/@components/JoinPage/EmailAuthenticationPage/index.tsx
  src/@components/JoinPage/EmailAuthenticationPage/style.ts
  src/@components/JoinPage/EmailConfirmPage/index.tsx
  src/core/join/agreeListsContents.ts
  src/util/checkInvalidEmail.ts
Labels: Refactor, 주함

#159 Feat/#158 joam
  package.json
  src/@components/JoinPage/AgreePage/index.tsx
  src/@components/JoinPage/EmailAuthenticationPage/index.tsx
  src/@components/JoinPage/EmailConfirmPage/index.tsx
  src/@components/JoinPage/UserInfoPage/UserEmail/index.tsx
  src/@components/JoinPage/UserInfoPage/UserEmail/style.ts
  src/@components/JoinPage/UserInfoPage/UserPassword/index.tsx
  src/@components/JoinPage/UserInfoPage/UserPassword/style.ts
  src/@components/JoinPage/UserInfoPage/index.tsx
  src/@components/JoinPage/UserInfoPage/style.ts
  src/@components/JoinPage/UserProfilePage/ProfileBirth/datepicker.d.ts
  src/@components/JoinPage/UserProfilePage/ProfileBirth/index.tsx
  src/@components/JoinPage/UserProfilePage/ProfileBirth/style.ts
  src/@components/JoinPage/UserProfilePage/ProfileGender/index.tsx
  src/@components/JoinPage/UserProfilePage/ProfileGender/style.ts
  src/@components/JoinPage/UserProfilePage/ProfileImage/index.tsx
  src/@components/JoinPage/UserProfilePage/ProfileImage/style.ts
  src/@components/JoinPage/UserProfilePage/ProfileNickname/index.tsx
  src/@components/JoinPage/UserProfilePage/ProfileNickname/style.ts
  src/@components/JoinPage/UserProfilePage/index.tsx
  src/@components/JoinPage/UserProfilePage/style.ts
  src/@components/JoinPage/index.tsx
  src/@components/LoginPage/@hooks/useLoginForm.ts
  src/@components/index.ts
  src/Router.tsx
  src/asset/icon/addProfileBtn.svg
  src/asset/icon/downArrow.svg
  src/asset/icon/index.ts
  src/asset/image/defaultBigProfile.png
  src/asset/image/index.tsx
  src/core/api/bookmark.ts
  src/core/api/cardCollection.ts
  src/core/api/common/constants.ts
  src/core/api/join.ts
  src/core/api/login.ts
  src/core/api/main.ts
  src/core/api/myPage.ts
  src/core/join/prevPages.ts
  src/core/join/userProfileErrorMsg.ts
  src/core/routes/path.ts
  src/mocks/handlers/cards.ts
  src/mocks/handlers/categories.ts
  src/mocks/handlers/users.ts
  src/types/join.ts
  src/types/users.ts
  src/util/checkInvalidPassword.ts
  yarn.lock
Labels: Refactor, 주함

#170 [ feat ] GTM classname 전부 삽입
  src/@components/@common/Header/index.tsx
  src/@components/@common/HeadingTitleContainer/index.tsx
  src/@components/@common/LoginModal/index.tsx
  src/@components/@common/MenuBar/index.tsx
  src/@components/CardCollectionPage/Card/LastCard/index.tsx
  src/@components/CardCollectionPage/CardSlider/index.tsx
  src/@components/CardCollectionPage/Tag/index.tsx
  src/@components/CategoryPage/index.tsx
  src/@components/JoinPage/AgreePage/index.tsx
  src/@components/JoinPage/EmailAuthenticationPage/index.tsx
  src/@components/JoinPage/UserInfoPage/index.tsx
  src/@components/JoinPage/UserProfilePage/index.tsx
  src/@components/MainPage/Banner/index.tsx
  src/@components/MainPage/BestPiickle/BestPiickleCard/index.tsx
  src/@components/MainPage/CTABtn/index.tsx
  src/@components/MainPage/PiickleMe/index.tsx
  src/@components/MyPage/MyPiickle/index.tsx
Labels: Feature, 지영

#163 feat/#161 JiYoungQA
  src/@components/@common/hooks/useOutClickCloser.ts
  src/@components/JoinPage/AgreePage/index.tsx
  src/@components/JoinPage/UserProfilePage/index.tsx
  src/core/api/common/constants.ts
  src/core/join/prevPages.ts
Labels: Fix, 지영

#164 feat/#162 NaYeonQA
  src/@components/@common/MenuBar/index.tsx
  src/@components/JoinPage/UserProfilePage/ProfileImage/index.tsx
  src/@components/JoinPage/UserProfilePage/ProfileNickname/index.tsx
  src/@components/JoinPage/UserProfilePage/index.tsx
  src/@components/MainPage/BestPiickle/index.tsx
  src/@components/MainPage/BestPiickle/style.ts
  src/@components/MyPage/MyInfo/index.tsx
  src/@components/MyPage/MyInfo/style.ts
  src/@components/MyPage/NicknameModal/index.tsx
  src/core/join/userProfileErrorMsg.ts
  src/util/checkInvalidNickName.ts
Labels: Fix, 나연

#168 Feat/#165 delete
  src/@components/DeletePage/index.tsx
  src/@components/DeletePage/style.ts
  src/@components/MyPage/MySetting/index.tsx
  src/@components/index.ts
  src/Router.tsx
  src/asset/icon/index.ts
  src/asset/icon/smallEmptyCheckBox.svg
  src/asset/icon/smallFullCheckBox.svg
  src/core/api/delete.ts
  src/core/delete/feedBackListsContents.ts
  src/core/routes/path.ts
Labels: Feature, 나연
