Repository TeamPiickle/client, pull requests merged in 2022-07, with the labels that each got.

#5 [ Common ] style theme font, color setting
  public/index.html
  src/index.tsx
  src/style/styled.d.ts
  src/style/theme.ts
Labels: Feature, 나연

#7 [ README ] 과제제출용 readme 작성
  README.md
Labels: Feature, 지영

#16 Feat/#15 header
  src/Router.tsx
  src/asset/icon/.keep
  src/asset/icon/hamburger.svg
  src/asset/icon/index.ts
  src/asset/icon/logo.svg
  src/components/common/Header/index.tsx
  src/components/common/Header/style.ts
  src/style/theme.ts
Labels: Feature, 주함

#19 Feat/#17 heading title
  .storybook/preview.js
  src/components/ExampleButton/index.stories.tsx
  src/components/ExampleButton/index.tsx
  src/components/ExampleButton/style.ts
  src/components/ExampleInput/index.stories.tsx
  src/components/ExampleInput/index.tsx
  src/components/ExampleInput/style.ts
  src/components/Main/common/.keep
  src/components/Main/common/HeadingTitleContainer/index.stories.tsx
  src/components/Main/common/HeadingTitleContainer/index.tsx
  src/components/Main/common/HeadingTitleContainer/style.ts
  src/core/main/headingTitles.ts
  src/core/temp.ts
  src/style/theme.ts
Labels: Feature, 주함

#20 Feat/#14 best_piickle
  package.json
  src/components/Main/BestPiickle/BestPiickleCard/index.tsx
  src/components/Main/BestPiickle/BestPiickleCard/style.ts
  src/components/Main/BestPiickle/index.tsx
  src/components/Main/BestPiickle/style.ts
  src/components/Main/index.tsx
  src/style/globalStyle.ts
  src/style/styled.d.ts
  src/style/theme.ts
  yarn.lock
Labels: Feature, 혜은

#23 Feat/#22 cta btn
  src/components/Main/CTABtn/index.stories.tsx
  src/components/Main/CTABtn/index.tsx
  src/components/Main/CTABtn/style.ts
Labels: Feature, 주함

#24 Feat/#18 piickle me
  src/asset/icon/index.ts
  src/asset/icon/voteImg1.svg
  src/asset/icon/voteImg2.svg
  src/components/Main/PiickleMe/index.tsx
  src/components/Main/PiickleMe/style.ts
  src/components/Main/index.tsx
Labels: Feature, 지영

#28 Feat/#26 swiper
  src/asset/icon/emptyHeart.svg
  src/asset/icon/filterBtn.svg
  src/asset/icon/index.ts
  src/asset/icon/nextCardBtn.svg
  src/components/CardCollection/Card/LastCard/index.tsx
  src/components/CardCollection/Card/LastCard/style.ts
  src/components/CardCollection/Card/index.tsx
  src/components/CardCollection/Card/style.ts
  src/components/CardCollection/CardSlider/index.tsx
  src/components/CardCollection/CardSlider/style.ts
  src/components/CardCollection/CustomFullHeart/index.tsx
  src/components/CardCollection/Tag/index.tsx
  src/components/CardCollection/Tag/style.ts
  src/components/CardCollection/TagsSlider/index.tsx
  src/components/CardCollection/TagsSlider/style.ts
  src/components/CardCollection/index.tsx
  src/components/CardCollection/style.ts
  src/components/Main/BestPiickle/BestPiickleCard/style.ts
  src/components/Main/BestPiickle/index.tsx
  src/components/Main/index.tsx
  src/components/Main/style.ts
  src/components/common/Header/index.tsx
  src/components/common/Header/style.ts
  src/style/theme.ts
Labels: Feature, 주함

#29 Feat/#25 axios
  src/core/api/cardCollection.ts
  src/core/api/common/axios.ts
  src/core/api/common/constants.ts
  src/core/api/index.ts
  src/core/api/login.ts
  src/core/api/main.ts
  src/core/api/myPage.ts
  src/core/api/vote.ts
Labels: Feature, 혜은

#30 Feat/#21 banner
  package.json
  src/components/Main/Banner/index.tsx
  src/components/Main/Banner/style.ts
  src/components/Main/index.tsx
  yarn.lock
Labels: Feature, 나연

#33 Feat/#31 footer
  src/components/Main/Footer/index.tsx
  src/components/Main/Footer/style.ts
  src/components/Main/index.tsx
Labels: Feature, 나연

#34 Feat/#31 mood piickle
  src/asset/image/MoodPiickle1.svg
  src/asset/image/MoodPiickle2.svg
  src/asset/image/MoodPiickle3.svg
  src/asset/image/index.tsx
  src/components/Main/MoodPiickle/index.tsx
  src/components/Main/MoodPiickle/style.ts
  src/components/Main/index.tsx
Labels: Feature, 나연

#44 [ Login ] 로그인 뷰 구현
  src/App.tsx
  src/asset/icon/MenuBar Profile.svg
  src/asset/icon/closeBtn.svg
  src/asset/icon/index.ts
  src/components/CardCollection/Card/LastCard/index.tsx
  src/components/Login/LoginForm/index.tsx
  src/components/Login/LoginForm/style.ts
  src/components/Login/index.tsx
  src/components/Main/CTABtn/index.tsx
  src/components/Main/MenuBar/index.tsx
  src/components/Main/MenuBar/style.ts
  src/components/common/Header/index.tsx
  src/components/common/Header/style.ts
Labels: Feature, 주함

#37 Feat/#36 filter modal
  package.json
  src/asset/icon/index.ts
  src/asset/icon/modalCloseBtn.svg
  src/components/CardCollection/CardSlider/index.tsx
  src/components/CardCollection/FilterModal/IntimacySlider/index.tsx
  src/components/CardCollection/FilterModal/IntimacySlider/style.ts
  src/components/CardCollection/FilterModal/index.tsx
  src/components/CardCollection/FilterModal/style.ts
  src/components/CardCollection/index.tsx
  src/components/Main/MenuBar/style.ts
  src/components/common/Modal/index.tsx
  src/components/common/Modal/style.ts
  src/style/theme.ts
  yarn.lock
Labels: Feature, 혜은

#42 Feat/#40 piickle me detail
  src/asset/icon/check1.svg
  src/asset/icon/check2.svg
  src/asset/icon/index.ts
  src/components/Vote/AfterVoteList/index.tsx
  src/components/Vote/AfterVoteList/style.ts
  src/components/Vote/BeforeVoteList/index.tsx
  src/components/Vote/BeforeVoteList/style.ts
  src/components/Vote/VoteContent/index.tsx
  src/components/Vote/VoteContent/style.ts
  src/components/Vote/VoteTitle/index.tsx
  src/components/Vote/VoteTitle/style.ts
  src/components/Vote/index.tsx
  src/core/vote/voteContent.ts
Labels: Feature, 지영

#45 [ CardCollection ] swiper view vh 조정
  src/App.tsx
  src/components/CardCollection/CardSlider/style.ts
  src/components/CardCollection/style.ts
  src/style/globalStyle.ts
Labels: Feature, Fix, 주함

#52 Feat/#47 login modal
  src/asset/icon/grayHeart.svg
  src/asset/icon/index.ts
  src/components/CardCollection/Card/index.tsx
  src/components/CardCollection/CardSlider/index.tsx
  src/components/CardCollection/LoginModal/index.tsx
  src/components/CardCollection/LoginModal/style.ts
  src/components/CardCollection/index.tsx
  src/components/Main/Footer/style.ts
Labels: Feature, 나연

#53 Feat/#50 category
  src/asset/image/categoryBanner.png
  src/asset/image/index.tsx
  src/components/Category/CategoryContents/index.tsx
  src/components/Category/CategoryContents/style.ts
  src/components/Category/index.tsx
  src/components/common/HeadingTitleContainer/style.ts
  src/core/category/categoryList.ts
Labels: Feature, 지영

#51 Feat/#49 mocking
  src/components/CardCollection/CardSlider/index.tsx
  src/components/CardCollection/FilterModal/index.tsx
  src/components/Main/BestPiickle/index.tsx
  src/components/Main/MoodPiickle/index.tsx
  src/components/Main/PiickleMe/index.tsx
  src/components/Main/PiickleMe/style.ts
  src/core/api/cardCollection.ts
  src/core/api/common/axios.ts
  src/core/api/common/constants.ts
  src/core/api/main.ts
  src/core/api/myPage.ts
  src/core/api/vote.ts
  src/mocks/handlers/ballots.ts
  src/mocks/handlers/cards.ts
  src/mocks/handlers/categories.ts
  src/mocks/handlers/index.ts
  src/mocks/handlers/users.ts
  src/types/cardCollection.ts
  src/types/main.ts
Labels: Feature, 주함

#57 [ Feat ] #56 swr
  package.json
  src/asset/image/.keep
  src/asset/image/MoodPiickle1.svg
  src/asset/image/MoodPiickle2.svg
  src/asset/image/MoodPiickle3.svg
  src/asset/image/index.tsx
  src/components/Bookmark/index.tsx
  src/components/Main/PiickleMe/index.tsx
  src/components/MyPage/MyInfo/index.tsx
  src/components/MyPage/index.tsx
  src/components/Vote/VoteContent/index.tsx
  src/core/api/bookmark.ts
  src/core/api/cardCollection.ts
  src/core/api/common/axios.ts
  src/core/api/main.ts
  src/core/api/myPage.ts
  src/core/api/vote.ts
  src/mocks/handlers/ballots.ts
  src/mocks/handlers/index.ts
  src/mocks/handlers/users.ts
  src/types/.keep
  yarn.lock
Labels: Feature, 주함

#70 Feat/#66 main mock 연결
  src/components/Main/BestPiickle/BestPiickleCard/index.tsx
  src/components/Main/BestPiickle/index.tsx
  src/components/Main/MoodPiickle/index.tsx
  src/components/Main/PiickleMe/index.tsx
  src/components/Main/PiickleMe/style.ts
Labels: Feature, 혜은

#68 [ feat ] MyPage 프로필 get 구현
  src/components/MyPage/MyInfo/index.tsx
  src/components/MyPage/MyInfo/style.ts
Labels: Feature, 나연

#64 Feat/#62 my piickle mock 연결
  src/components/Bookmark/MyPiickleItem/index.tsx
  src/components/Bookmark/index.tsx
Labels: Feature, 혜은

#65 Feat/#60 mock api login
  src/components/Login/LoginForm/index.tsx
  src/core/api/common/axios.ts
  src/core/atom/login.ts
  src/mocks/handlers/users.ts
Labels: Feature, 주함

#67 Feat/#63 mock api category
  src/components/Category/CategoryContents/index.tsx
  src/components/Vote/BeforeVoteList/index.tsx
  src/core/category/categoryList.ts
  src/index.tsx
Labels: Feature, 지영

#71 [ Feat ] #61 mock api card collection
  src/components/CardCollection/Card/index.tsx
  src/components/CardCollection/Card/style.ts
  src/components/CardCollection/CardSlider/index.tsx
  src/components/CardCollection/FilterModal/index.tsx
  src/components/CardCollection/Tag/index.tsx
  src/components/CardCollection/TagsSlider/index.tsx
  src/components/CardCollection/TagsSlider/style.ts
  src/components/CardCollection/index.tsx
  src/core/api/cardCollection.ts
  src/core/cardCollection/filter.ts
  src/core/cardCollection/slider.ts
  src/index.tsx
  src/mocks/handlers/cards.ts
  src/types/cardCollection.ts
Labels: Feature, 주함

#73 Feat/#69 checking UI
  src/components/Main/Banner/index.tsx
  src/components/Main/Banner/style.ts
  src/components/common/Footer/index.tsx
  src/components/common/Footer/style.ts
  src/components/common/Header/style.ts
Labels: Feature, 나연

#74 Feat/#72 hyeeun QA
  src/asset/image/categoryBanner.png
  src/asset/image/index.tsx
  src/components/Category/CategoryContents/index.tsx
  src/components/Category/index.tsx
  src/components/Category/style.ts
  src/components/Main/MenuBar/style.ts
  src/components/MyPage/MyPiickle/index.tsx
  src/components/common/MenuBar/index.tsx
  src/components/common/MenuBar/style.ts
  src/core/api/common/axios.ts
  src/core/category/categoryList.ts
  src/core/main/headingTitles.ts
Labels: Feature, Refactor, Fix, 혜은

#77 Feat/#69 checking UI
  src/components/CardCollection/Card/style.ts
  src/components/CardCollection/CardSlider/index.tsx
  src/components/CardCollection/FilterModal/index.tsx
  src/components/Category/CategoryContents/index.tsx
  src/components/Category/index.tsx
  src/components/Login/LoginForm/index.tsx
  src/components/Main/Banner/index.tsx
  src/components/Main/Banner/style.ts
  src/components/Main/BestPiickle/BestPiickleCard/index.tsx
  src/components/Main/BestPiickle/BestPiickleCard/style.ts
  src/components/Main/BestPiickle/index.tsx
  src/components/Main/MoodPiickle/index.tsx
  src/components/Main/MoodPiickle/style.ts
  src/components/common/MenuBar/index.tsx
  src/core/api/main.ts
  src/core/atom/login.ts
  src/core/atom/sliderIdx.ts
  src/mocks/handlers/cards.ts
  src/mocks/handlers/categories.ts
  src/types/cardCollection.ts
Labels: Feature, 나연

#80 Feat/#72 hyeeun qa
  src/components/Bookmark/MyPiickleItem/style.ts
  src/components/CardCollection/Card/index.tsx
  src/components/CardCollection/FilterModal/style.ts
  src/components/CardCollection/LoginModal/index.tsx
  src/components/CardCollection/LoginModal/style.ts
  src/components/Category/CategoryContents/style.ts
  src/components/Login/LoginForm/style.ts
  src/components/Main/BestPiickle/BestPiickleCard/index.tsx
  src/components/Main/BestPiickle/BestPiickleCard/style.ts
  src/components/Main/CTABtn/style.ts
  src/components/Vote/AfterVoteList/index.tsx
  src/components/common/Header/index.tsx
  src/components/common/Header/style.ts
  src/components/common/MenuBar/style.ts
  src/components/common/Modal/style.ts
  src/core/api/main.ts
  src/core/cardCollection/filter.ts
  src/style/theme.ts
Labels: Feature, Refactor, Fix, 혜은

#75 Feat/#63 mock api category
  src/components/CardCollection/LoginModal/index.tsx
  src/components/CardCollection/index.tsx
  src/components/Vote/AfterVoteList/index.tsx
  src/components/Vote/AfterVoteList/style.ts
  src/components/Vote/BeforeVoteList/index.tsx
  src/components/Vote/VoteContent/index.tsx
  src/mocks/handlers/ballots.ts
Labels: Feature, 지영

#84 Feat/#78 jiyeong qa
  src/components/Main/Banner/style.ts
  src/components/Vote/AfterVoteList/index.tsx
  src/components/Vote/AfterVoteList/style.ts
  src/components/Vote/BeforeVoteList/index.tsx
  src/components/Vote/BeforeVoteList/style.ts
  src/components/Vote/VoteContent/style.ts
  src/components/Vote/VoteTitle/style.ts
  src/components/common/Header/style.ts
  src/index.tsx
Labels: Feature, Refactor, Fix, 지영

#88 Feat/#86 joam qa
  src/asset/image/defaultProfile.png
  src/asset/image/index.tsx
  src/asset/image/piickleLoading.gif
  src/components/CardCollection/CardSlider/index.tsx
  src/components/CardCollection/FilterModal/index.tsx
  src/components/CardCollection/LoginModal/index.tsx
  src/components/CardCollection/LoginModal/style.ts
  src/components/CardCollection/TagsSlider/index.tsx
  src/components/CardCollection/index.tsx
  src/components/Category/CategoryContents/index.tsx
  src/components/Error404/index.tsx
  src/components/Error404/style.ts
  src/components/Main/BestPiickle/BestPiickleCard/index.tsx
  src/components/Main/BestPiickle/index.tsx
  src/components/Main/MoodPiickle/index.tsx
  src/components/Main/PiickleMe/index.tsx
  src/components/Main/index.tsx
  src/components/MyPage/MyInfo/index.tsx
  src/components/common/Loading/index.tsx
  src/components/common/Loading/style.ts
  src/core/api/cardCollection.ts
  src/core/api/common/axios.ts
  src/core/api/main.ts
  src/core/api/myPage.ts
  src/index.tsx
  src/types/cardCollection.ts
  src/types/main.ts
  src/types/users.ts
  src/util/fetchCardCollection.ts
Labels: Feature, 주함

#91 Feat/#83 hyeeun qa
  src/core/api/cardCollection.ts
  src/core/api/common/axios.ts
  src/index.tsx
Labels: Feature, Refactor, Fix, 혜은

#95 Feat/#83 hyeeun qa
  src/components/Main/MoodPiickle/index.tsx
  src/components/common/MenuBar/index.tsx
  src/components/common/MenuBar/style.ts
Labels: Feature, Fix, 혜은

#96 Feat/#86 joam qa1
  src/components/Bookmark/MyPiickleItem/index.tsx
  src/components/Bookmark/index.tsx
  src/components/CardCollection/Card/index.tsx
  src/components/CardCollection/CardSlider/index.tsx
  src/components/CardCollection/CardSlider/style.ts
  src/components/CardCollection/CustomFullHeart/index.tsx
  src/components/CardCollection/FilterModal/index.tsx
  src/components/Login/LoginForm/index.tsx
  src/components/MyPage/MyInfo/index.tsx
  src/components/MyPage/NicknameModal/index.tsx
  src/components/Vote/AfterVoteList/index.tsx
  src/components/Vote/BeforeVoteList/index.tsx
  src/components/Vote/VoteContent/index.tsx
  src/core/api/bookmark.ts
  src/core/api/cardCollection.ts
  src/core/api/login.ts
  src/core/api/myPage.ts
  src/core/api/vote.ts
  src/types/cardCollection.ts
  src/util/fetchCardCollection.ts
Labels: Feature, 주함

#100 [ fix ] 로그인 에러 로직 수정
  src/components/Bookmark/MyPiickleItem/index.tsx
  src/components/Bookmark/MyPiickleItem/style.ts
  src/components/Login/LoginForm/index.tsx
  src/core/api/bookmark.ts
Labels: Feature, 주함

#97 Feat/#93 nayeon qa
  src/components/CardCollection/Card/index.tsx
  src/components/CardCollection/CardSlider/index.tsx
  src/components/CardCollection/Tag/style.ts
  src/components/Main/MoodPiickle/style.ts
  src/components/MyPage/MyInfo/index.tsx
  src/components/MyPage/NicknameModal/index.tsx
  src/components/Vote/BeforeVoteList/index.tsx
  src/components/Vote/VoteContent/style.ts
  src/components/common/LoginModal/index.tsx
Labels: Feature, Fix, 나연

#102 Feat/#93 nayeon qa
  src/asset/image/index.tsx
  src/asset/image/mainbanner01.jpg
  src/asset/image/mainbanner02.jpg
  src/components/Category/style.ts
  src/components/Main/Banner/index.tsx
  src/components/Main/Banner/style.ts
  src/components/Vote/AfterVoteList/style.ts
  src/components/Vote/BeforeVoteList/style.ts
  src/components/common/Footer/index.tsx
  src/core/main/headingTitles.ts
Labels: Feature, Fix, 나연

#107 Feat/#86 joam qa2
  src/components/CardCollection/CardSlider/index.tsx
  src/components/CardCollection/FilterModal/index.tsx
  src/components/CardCollection/index.tsx
  src/core/atom/slider.ts
Labels: Feature, Fix, 주함

#103 [ etc ] HTML meta태그 설정
  public/index.html
Labels: Feature, 지영

#106 Feat/#83 hyeeun qa
  src/components/Main/BestPiickle/index.tsx
  src/components/MyPage/MyInfo/index.tsx
  src/components/MyPage/MyInfo/style.ts
  src/components/common/Loading/index.tsx
  src/components/common/LoginModal/index.tsx
  src/components/common/MenuBar/index.tsx
  src/components/common/MenuBar/style.ts
  src/components/common/Modal/style.ts
  src/core/api/myPage.ts
  src/mocks/handlers/users.ts
  src/types/users.ts
Labels: Feature, Fix, 혜은

#108 Feat/#105 category bg edit
  src/components/Bookmark/MyPiickleItem/index.tsx
  src/components/Bookmark/MyPiickleItem/style.ts
  src/components/Bookmark/index.tsx
  src/components/CardCollection/Card/index.tsx
  src/components/CardCollection/CardSlider/index.tsx
  src/components/CardCollection/Tag/style.ts
  src/components/Category/CategoryContents/index.tsx
  src/components/Category/CategoryContents/style.ts
  src/components/Login/LoginForm/index.tsx
  src/components/Main/BestPiickle/index.tsx
  src/components/Main/CTABtn/style.ts
  src/components/Main/MoodPiickle/index.tsx
  src/components/Main/MoodPiickle/style.ts
  src/components/Main/PiickleMe/index.tsx
  src/components/MyPage/MyInfo/index.tsx
  src/components/MyPage/NicknameModal/index.tsx
  src/components/Vote/BeforeVoteList/index.tsx
  src/components/Vote/VoteContent/index.tsx
  src/components/Vote/VoteContent/style.ts
  src/components/common/LoginModal/index.tsx
  src/components/common/MenuBar/index.tsx
  src/core/api/bookmark.ts
  src/index.tsx
  src/style/theme.ts
Labels: Fix, 지영

#115 Feat/#112 joam
  package.json
  public/index.html
  src/asset/image/favicon-96x96.png
  src/asset/image/index.tsx
  src/asset/image/mainbanner01.jpg
  src/asset/image/mainbanner02.jpg
  src/components/CardCollection/CardSlider/index.tsx
  src/components/CardCollection/CardSlider/style.ts
  src/components/CardCollection/CustomFullHeart/index.tsx
  src/components/CardCollection/FilterModal/index.tsx
  src/components/CardCollection/index.tsx
  src/components/Category/CategoryContents/style.ts
  src/components/Category/style.ts
  src/components/Main/Banner/index.tsx
  src/components/Main/Banner/style.ts
  src/components/Main/BestPiickle/index.tsx
  src/components/Main/MoodPiickle/style.ts
  src/components/MyPage/MyInfo/index.tsx
  src/components/MyPage/MyInfo/style.ts
  src/components/MyPage/MySetting/index.tsx
  src/components/Vote/AfterVoteList/style.ts
  src/components/Vote/BeforeVoteList/style.ts
  src/components/common/Footer/index.tsx
  src/components/common/LoginModal/index.tsx
  src/components/common/MenuBar/index.tsx
  src/components/common/MenuBar/style.ts
  src/components/common/Modal/style.ts
  src/core/api/cardCollection.ts
  src/core/api/common/axios.ts
  src/core/atom/slider.ts
  src/core/main/headingTitles.ts
  src/mocks/handlers/users.ts
  src/style/globalStyle.ts
  src/types/users.ts
  yarn.lock
Labels: Feature, Fix, 주함

#118 Feat/#117 mood piickle edit
  src/components/Main/MoodPiickle/index.tsx
  src/components/Main/MoodPiickle/style.ts
  src/core/main/moodPiickle.ts
Labels: Refactor, 지영

#122 Feat/#119 mobile usability
  public/index.html
  src/components/CardCollection/CardSlider/style.ts
  src/components/CardCollection/index.tsx
  src/components/Category/index.tsx
  src/components/Main/Banner/index.tsx
  src/components/Main/Banner/style.ts
  src/components/Main/BestPiickle/style.ts
  src/components/MyPage/index.tsx
  src/core/main/banner.ts
  src/style/globalStyle.ts
  src/util/hooks/useScroll.ts
Labels: Feature, 주함

#121 Feat/#120-mobile_height_bug
  src/App.tsx
  src/components/CardCollection/style.ts
  src/components/common/Loading/style.ts
Labels: Feature, Fix, 혜은
