Repository TeamPiickle/client, pull requests merged in 2023-01, with the labels that each got.

#177 Hotfix/delete mail auth
  src/@components/@common/LoginModal/index.tsx
  src/@components/@common/MenuBar/ProfileContainer/DefaultProfileContainer.tsx
  src/@components/JoinPage/AgreePage/index.tsx
  src/@components/JoinPage/EmailAuthenticationPage/index.tsx
  src/@components/JoinPage/EmailAuthenticationPage/style.ts
  src/@components/JoinPage/EmailConfirmPage/index.tsx
  src/@components/JoinPage/EmailConfirmPage/style.ts
  src/@components/JoinPage/UserInfoPage/UserEmail/index.tsx
  src/@components/JoinPage/UserInfoPage/UserEmail/style.ts
  src/@components/JoinPage/UserInfoPage/UserPassword/index.tsx
  src/@components/JoinPage/UserInfoPage/UserPassword/style.ts
  src/@components/JoinPage/UserInfoPage/index.tsx
  src/@components/JoinPage/UserProfilePage/index.tsx
  src/@components/LoginPage/LoginForm/index.tsx
  src/Router.tsx
  src/core/api/join.ts
  src/core/join/subHeaderInfo.ts
  src/core/routes/path.ts
Labels: Feature, Fix, 나연

#178 [ Hotfix ] 회원가입 이메일, 비밀번호 입력 로직 리팩토링
  src/@components/JoinPage/EmailAuthenticationPage/index.tsx
  src/@components/JoinPage/EmailConfirmPage/index.tsx
  src/@components/JoinPage/UserInfoPage/UserEmail/index.tsx
  src/@components/JoinPage/UserInfoPage/UserEmail/style.ts
  src/@components/JoinPage/UserInfoPage/UserPassword/index.tsx
  src/@components/JoinPage/UserInfoPage/UserPassword/style.ts
  src/@components/JoinPage/UserInfoPage/hooks/useEmail.ts
  src/@components/JoinPage/UserInfoPage/hooks/usePasswords.ts
  src/@components/JoinPage/UserInfoPage/index.tsx
  src/core/join/emailErrorMessage.ts
  src/core/join/userInfoInputErrorMessage.ts
Labels: Refactor, Fix

#180 [ feat ] footer 항목 변경 및 링크 추가
  src/@components/@common/Footer/index.tsx
Labels: Feature, Fix, 나연

#182 Feat/#181 sub text
  src/@components/@common/HeadingTitleContainer/style.ts
  src/core/main/headingTitles.ts
Labels: Feature, 나연

#184 Feat/#183 pagination
  src/@components/VotePage/VoteContent/AfterVoteList/index.tsx
  src/@components/VotePage/VoteContent/AfterVoteList/style.ts
  src/@components/VotePage/VoteContent/BeforeVoteList/index.tsx
  src/@components/VotePage/VoteContent/BeforeVoteList/style.ts
  src/@components/VotePage/VoteContent/index.tsx
  src/@components/VotePage/VoteContent/style.ts
  src/@components/VotePage/VoteTitle/index.tsx
  src/@components/VotePage/VoteTitle/style.ts
  src/@components/VotePage/index.tsx
  src/core/api/vote.ts
  src/style/theme.ts
  src/types/ballots.ts
Labels: Feature, 주함

#186 Feat/#185 moodpiickle design
  src/@components/@common/HeadingTitleContainer/style.ts
  src/@components/CategoryPage/CategoryContents/index.tsx
  src/@components/CategoryPage/CategoryContents/style.ts
  src/@components/CategoryPage/index.tsx
  src/@components/CategoryPage/style.ts
  src/@components/MainPage/MoodPiickle/index.tsx
  src/@components/MainPage/MoodPiickle/style.ts
  src/asset/image/categoryBanner.png
  src/core/category/categoryList.ts
  src/style/theme.ts
  src/types/main.ts
Labels: Feature, 나연

#188 Feat/#187 upgrade main
  src/@components/@common/Footer/style.ts
  src/@components/@common/HeadingTitleContainer/style.ts
  src/@components/CategoryPage/CategoryContents/index.tsx
  src/@components/MainPage/Banner/style.ts
  src/@components/MainPage/BestPiickle/BestPiickleCard/index.tsx
  src/@components/MainPage/BestPiickle/BestPiickleCard/style.ts
  src/@components/MainPage/BestPiickle/index.tsx
  src/@components/MainPage/BestPiickle/style.ts
  src/@components/MainPage/CTABtn/style.ts
  src/@components/MainPage/MoodPiickle/index.tsx
  src/@components/MainPage/MoodPiickle/style.ts
  src/@components/MainPage/PiickleMe/index.tsx
  src/@components/MainPage/PiickleMe/style.ts
  src/asset/icon/index.ts
  src/asset/icon/voteImg.svg
  src/asset/image/index.tsx
  src/asset/image/voteBanner.png
  src/style/theme.ts
Labels: Feature, Refactor, Fix, 나연
