Repository TeamPiickle/client, pull requests merged in 2023-03, with the labels that each got.

#222 feat: add image container for compatibility
  src/@components/CategoryPage/style.ts
  src/@components/MainPage/Banner/index.tsx
  src/@components/MainPage/PiickleMe/style.ts
  src/asset/image/origin/index.tsx
  src/util/main/banner.ts
Labels: Feature, 주함

#230 feat: scrollable container custom hook
  src/@components/@common/hooks/useScrollableContainer.ts
  src/@components/MainPage/BestPiickle/index.tsx
  src/@components/MainPage/Medley/index.tsx
Labels: Feature, 주함

#231 Hotfix/#218 메들리 기능 이슈 해결
  src/@components/MainPage/Medley/MedleyCard/index.tsx
  src/@components/MainPage/Medley/MedleyCard/style.ts
  src/@components/MainPage/Medley/index.tsx
  src/@components/MainPage/hooks/useMedleyLists.ts
  src/util/main/medleyGradation.ts
Labels: Feature, 주함

#235 #233 카테고리 배너 재조정
  package.json
  src/@components/CategoryPage/index.tsx
  src/@components/CategoryPage/style.ts
  src/@components/MainPage/Banner/index.tsx
  yarn.lock
Labels: Feature, 주함

#240 Feat/#233 menubar
  src/@components/@common/MenuBar/index.tsx
  src/@components/@common/MenuBar/style.ts
Labels: Feature, Fix, 나연

#238 Feat/#234 banner medley login
  src/@components/MainPage/Medley/index.tsx
  src/@components/MainPage/Medley/style.ts
  src/@components/MainPage/StripBanner/index.tsx
  src/@components/MainPage/StripBanner/style.ts
  src/@components/MainPage/index.tsx
  src/asset/image/banner_3.webp
  src/asset/image/index.tsx
  src/asset/image/medleyBanner.webp
  src/asset/image/origin/banner_3.png
  src/asset/image/origin/index.tsx
  src/asset/image/origin/medleyBanner.png
  src/asset/image/origin/stripBanner.png
  src/asset/image/stripBanner.webp
  src/style/theme.ts
  src/util/main/banner.ts
  src/util/main/medleyGradation.ts
Labels: Feature, Fix, 나연

#245 [ feat ] menubar list의 title/subTitle 수정
  src/@components/@common/MenuBar/index.tsx
Labels: Feature, 나연

#244 Bug/#233 filter modal
  src/@components/@common/Modal/index.tsx
  src/@components/CardCollectionPage/FilterModal/style.ts
Labels: Feature, Fix, 나연

#248 Feat/#233 banner style
  src/@components/MainPage/Medley/index.tsx
  src/@components/MainPage/Medley/style.ts
  src/@components/MainPage/StripBanner/style.ts
Labels: Feature, Fix, 나연

#247 #233 메들리 스와이퍼 시 클릭 방지
  src/@components/MainPage/Medley/MedleyCard/index.tsx
  src/@components/MainPage/Medley/index.tsx
Labels: Feature, Fix, 주함

#243 [ feat ] opacity 클릭 시, modal 닫기 기능만 작동하도록 구현
  src/@components/@common/hooks/useOutClickCloser.ts
Labels: Feature, Fix, 나연

#252 release/1.3 -> develop (GTM)
  src/@components/MainPage/BestPiickle/BestPiickleCard/index.tsx
  src/@components/MainPage/Medley/MedleyCard/index.tsx
  src/@components/MainPage/PiickleMe/index.tsx
  src/asset/icon/logo.svg
Labels: git😎

#253 Hotfix/mobile join
  src/@components/JoinPage/AgreePage/index.tsx
  src/@components/JoinPage/UserProfilePage/index.tsx
Labels: Bug, Fix, 나연
