Repository TeamPiickle/client, pull requests merged in 2023-02, with the labels that each got.

#190 Feat/#189 footer
  src/@components/@common/Footer/style.ts
Labels: Fix, 나연

#192 Feat/#189 vote cta btn
  src/@components/VotePage/VoteContent/index.tsx
  src/@components/VotePage/VoteContent/style.ts
Labels: Feature, Fix, 나연

#195 Bug/#189 fix category params name
  src/core/api/cardCollection.ts
Labels: Fix, 주함

#197 Feat/#196 modify gtm
  src/@components/@common/Header/index.tsx
  src/@components/@common/HeadingTitleContainer/index.tsx
  src/@components/@common/LoginModal/index.tsx
  src/@components/@common/MenuBar/ProfileContainer/DefaultProfileContainer.tsx
  src/@components/@common/MenuBar/ProfileContainer/index.tsx
  src/@components/@common/MenuBar/index.tsx
  src/@components/@common/Modal/index.tsx
  src/@components/CardCollectionPage/Card/LastCard/index.tsx
  src/@components/CardCollectionPage/Card/index.tsx
  src/@components/CardCollectionPage/CardSlider/index.tsx
  src/@components/CardCollectionPage/FilterModal/index.tsx
  src/@components/CardCollectionPage/Tag/index.tsx
  src/@components/CategoryPage/CategoryContents/index.tsx
  src/@components/CategoryPage/index.tsx
  src/@components/JoinPage/AgreePage/index.tsx
  src/@components/JoinPage/EmailAuthenticationPage/index.tsx
  src/@components/JoinPage/UserInfoPage/index.tsx
  src/@components/JoinPage/UserProfilePage/index.tsx
  src/@components/MainPage/Banner/index.tsx
  src/@components/MainPage/BestPiickle/BestPiickleCard/index.tsx
  src/@components/MainPage/CTABtn/index.tsx
  src/@components/MainPage/MoodPiickle/index.tsx
  src/@components/MainPage/PiickleMe/index.tsx
  src/@components/MainPage/PiickleMe/style.ts
  src/@components/MyPage/MyPiickle/index.tsx
  src/@components/VotePage/VoteContent/BeforeVoteList/index.tsx
  src/@components/VotePage/VoteContent/index.tsx
  src/util/const/gtm.ts
Labels: Feature, 주함

#198 Bug/#196 gtm correct
  src/@components/@common/Header/index.tsx
  src/@components/@common/MenuBar/index.tsx
  src/@components/CardCollectionPage/Card/index.tsx
  src/@components/CategoryPage/CategoryContents/index.tsx
  src/@components/MainPage/MoodPiickle/index.tsx
  src/@components/VotePage/VoteContent/BeforeVoteList/index.tsx
Labels: Fix, 주함

#200 [ feat ] change footer notion link
  src/@components/@common/Footer/index.tsx
Labels: Feature, 나연

#202 fix: GTM class correct (no bubbling...)
  src/asset/icon/emptyHeart.svg
  src/asset/icon/hamburger.svg
Labels: Bug

#203 Align Develop from Release/1.2
  src/@components/@common/Footer/index.tsx
  src/@components/@common/Footer/style.ts
  src/@components/@common/Header/index.tsx
  src/@components/@common/HeadingTitleContainer/index.tsx
  src/@components/@common/LoginModal/index.tsx
  src/@components/@common/MenuBar/ProfileContainer/DefaultProfileContainer.tsx
  src/@components/@common/MenuBar/ProfileContainer/index.tsx
  src/@components/@common/MenuBar/index.tsx
  src/@components/@common/Modal/index.tsx
  src/@components/CardCollectionPage/Card/LastCard/index.tsx
  src/@components/CardCollectionPage/Card/index.tsx
  src/@components/CardCollectionPage/CardSlider/index.tsx
  src/@components/CardCollectionPage/FilterModal/index.tsx
  src/@components/CardCollectionPage/Tag/index.tsx
  src/@components/CategoryPage/CategoryContents/index.tsx
  src/@components/CategoryPage/index.tsx
  src/@components/CategoryPage/style.ts
  src/@components/JoinPage/AgreePage/index.tsx
  src/@components/JoinPage/EmailAuthenticationPage/index.tsx
  src/@components/JoinPage/UserInfoPage/index.tsx
  src/@components/JoinPage/UserProfilePage/index.tsx
  src/@components/MainPage/Banner/index.tsx
  src/@components/MainPage/BestPiickle/BestPiickleCard/index.tsx
  src/@components/MainPage/BestPiickle/BestPiickleCard/style.ts
  src/@components/MainPage/BestPiickle/index.tsx
  src/@components/MainPage/BestPiickle/style.ts
  src/@components/MainPage/CTABtn/index.tsx
  src/@components/MainPage/MoodPiickle/index.tsx
  src/@components/MainPage/PiickleMe/index.tsx
  src/@components/MainPage/PiickleMe/style.ts
  src/@components/MyPage/MyPiickle/index.tsx
  src/@components/VotePage/VoteContent/BeforeVoteList/index.tsx
  src/@components/VotePage/VoteContent/index.tsx
  src/@components/VotePage/VoteContent/style.ts
  src/asset/icon/emptyHeart.svg
  src/asset/icon/filterBtn.svg
  src/asset/icon/hamburger.svg
  src/asset/icon/index.ts
  src/asset/icon/smallRightArrow.svg
  src/core/api/cardCollection.ts
  src/util/const/gtm.ts
Labels: 주함, 나연, git😎

#207 Feat/#206 button
  src/@components/MainPage/BestPiickle/BestPiickleCard/index.tsx
  src/@components/MainPage/BestPiickle/BestPiickleCard/style.ts
  src/@components/MainPage/PiickleMe/index.tsx
  src/@components/MainPage/PiickleMe/style.ts
Labels: Feature, 나연

#209 Feat/#205 devising swiper
  src/@components/MainPage/BestPiickle/index.tsx
  src/@components/MainPage/BestPiickle/style.ts
Labels: Feature, 주함

#208 Feat/#114 image compression (+webp)
  package.json
  src/@components/JoinPage/UserProfilePage/ProfileImage/index.tsx
  src/@components/JoinPage/UserProfilePage/index.tsx
  src/@components/MainPage/Banner/index.tsx
  src/asset/asset.d.ts
  src/asset/image/banner_1.webp
  src/asset/image/banner_2.webp
  src/asset/image/banner_3.webp
  src/asset/image/categoryBanner.webp
  src/asset/image/defaultBigProfile.webp
  src/asset/image/defaultProfile.webp
  src/asset/image/index.tsx
  src/asset/image/origin/banner_1.png
  src/asset/image/origin/banner_2.png
  src/asset/image/origin/banner_3.png
  src/asset/image/origin/categoryBanner.png
  src/asset/image/origin/defaultBigProfile.png
  src/asset/image/origin/defaultProfile.png
  src/asset/image/origin/piickleLoading.gif
  src/asset/image/origin/voteBanner.png
  src/asset/image/piickleLoading.webp
  src/asset/image/voteBanner.webp
  src/util/imageCompressor.ts
  yarn.lock
Labels: Feature, 주함

#211 Feat/#210 card collection filter UI
  src/@components/@common/Modal/Portal.tsx
  src/@components/@common/Modal/index.tsx
  src/@components/@common/Modal/style.ts
  src/@components/CardCollectionPage/FilterModal/@hooks/useFilterTags.ts
  src/@components/CardCollectionPage/FilterModal/IntimacySlider/index.tsx
  src/@components/CardCollectionPage/FilterModal/IntimacySlider/style.ts
  src/@components/CardCollectionPage/FilterModal/index.tsx
  src/@components/CardCollectionPage/FilterModal/style.ts
  src/App.tsx
  src/core/cardCollection/filter.ts
  src/style/theme.ts
Labels: Feature, 주함

#212 Release/1.3 from forked Release/1.3
  README.md
  package.json
  src/@components/@common/Modal/style.ts
Labels: git😎

#214 Feat/#213 menubar
  src/@components/@common/MenuBar/ProfileContainer/DefaultProfileContainer.tsx
  src/@components/@common/MenuBar/ProfileContainer/index.tsx
  src/@components/@common/MenuBar/ProfileContainer/style.ts
  src/@components/@common/MenuBar/index.tsx
  src/@components/@common/MenuBar/style.ts
  src/@components/@common/hooks/useOutClickCloser.ts
  src/@components/DeletePage/index.tsx
  src/@components/JoinPage/AgreePage/index.tsx
  src/style/theme.ts
Labels: Feature, 나연

#216 Fix/#215 keep join infos
  src/@components/JoinPage/AgreePage/index.tsx
  src/@components/JoinPage/UserInfoPage/hooks/useEmail.ts
  src/@components/JoinPage/UserInfoPage/hooks/usePasswords.ts
  src/@components/JoinPage/UserInfoPage/index.tsx
  src/@components/JoinPage/UserProfilePage/ProfileBirth/index.tsx
  src/@components/JoinPage/UserProfilePage/ProfileGender/index.tsx
  src/@components/JoinPage/UserProfilePage/ProfileImage/index.tsx
  src/@components/JoinPage/UserProfilePage/ProfileNickname/index.tsx
  src/@components/JoinPage/UserProfilePage/index.tsx
  src/@components/JoinPage/index.tsx
  src/core/join/formData.ts
  src/core/join/userProfileErrorMessage.ts
Labels: Feature, Fix, 주함

#217 Hotfix/#215 keep join infos
  src/@components/JoinPage/AgreePage/index.tsx
  src/@components/JoinPage/UserInfoPage/hooks/usePasswords.ts
  src/@components/JoinPage/UserInfoPage/index.tsx
  src/@components/JoinPage/index.tsx
  src/core/join/userProfileErrorMessage.ts
Labels: Fix, 주함
