Repository TeamPiickle/client, pull requests merged in 2023-08, with the labels that each got.

#313 Feat/#312 card menu
  src/@components/@common/Modal/index.tsx
  src/@components/@common/Toast/ToastProvider.tsx
  src/@components/@common/Toast/context.ts
  src/@components/@common/Toast/hooks/useTimeout.ts
  src/@components/@common/Toast/hooks/useToast.ts
  src/@components/@common/Toast/style.ts
  src/@components/CardCollectionPage/Card/CardMenu/index.tsx
  src/@components/CardCollectionPage/Card/CardMenu/style.ts
  src/@components/CardCollectionPage/Card/MenuModal/index.tsx
  src/@components/CardCollectionPage/Card/MenuModal/style.ts
  src/@components/CardCollectionPage/Card/index.tsx
  src/@components/CardCollectionPage/Card/style.ts
  src/@components/CardCollectionPage/CardSlider/index.tsx
  src/@components/CardCollectionPage/index.tsx
  src/App.tsx
  src/asset/icon/IcBookmarkCheck_23_28.tsx
  src/asset/icon/IcMenuBtn.tsx
  src/asset/icon/IcShareBtn.tsx
Labels: Feature, 은형

#310 Feat/#305 main design
  src/@components/@common/hooks/useNavigateCardCollection.ts
  src/@components/@common/hooks/useRecentlyBookmarked.ts
  src/@components/BestPiicklePage/BestPiickleRank/RankItem/style.ts
  src/@components/BestPiicklePage/BestPiickleRank/index.tsx
  src/@components/BestPiicklePage/BestPiickleRecommend/RecommendItem/index.tsx
  src/@components/BestPiicklePage/BestPiickleRecommend/hooks/useRecentlyBookmarked.ts
  src/@components/BestPiicklePage/BestPiickleRecommend/index.tsx
  src/@components/CardCollectionPage/hooks/useCardLists.ts
  src/@components/MainPage/Banner/Slide/index.tsx
  src/@components/MainPage/Banner/Slide/style.ts
  src/@components/MainPage/Banner/SlideContent/index.tsx
  src/@components/MainPage/Banner/SlideContent/style.ts
  src/@components/MainPage/Banner/index.tsx
  src/@components/MainPage/Banner/style.ts
  src/@components/MainPage/Medley/MedleyCard/index.tsx
  src/@components/MainPage/Medley/MedleyCard/style.ts
  src/@components/MainPage/PiickleMe/style.ts
  src/@components/MainPage/TopicLink/index.tsx
  src/@components/MainPage/TopicLink/style.ts
  src/@components/MainPage/hooks/useRecentlyUpdated.ts
  src/@components/MainPage/index.tsx
  src/@components/MyPage/MySetting/index.tsx
  src/asset/image/banner_1.webp
  src/asset/image/banner_2.webp
  src/asset/image/index.tsx
  src/asset/image/new_banner_1.webp
  src/asset/image/new_banner_2.webp
  src/asset/image/new_banner_3.webp
  src/asset/image/origin/banner_1.png
  src/asset/image/origin/banner_2.png
  src/asset/image/origin/index.tsx
  src/asset/image/origin/new_banner_1.png
  src/asset/image/origin/new_banner_2.png
  src/asset/image/origin/new_banner_3.png
  src/asset/image/origin/topic_link_banner.png
  src/asset/image/topic_link_banner.webp
  src/core/api/common/constants.ts
  src/types/cardCollection.ts
  src/util/const/externalLinks.ts
  src/util/main/banner.ts
Labels: Feature, 은형

#318 Feat/#314 share card
  package.json
  src/@components/@common/hooks/useNavigateCardCollection.ts
  src/@components/CardCollectionPage/Card/CardMenu/index.tsx
  src/@components/CardCollectionPage/hooks/useCardLists.ts
  src/@components/CardCollectionPage/hooks/useCardShare.ts
  src/env.d.ts
  src/types/cardCollection.ts
  yarn.lock
Labels: Feature, 나연

#320 Bug/#311 mime type
  index.html
  src/@components/OAuthPage/OAuthKakaoPage/index.tsx
  src/env.d.ts
  vite.config.ts
Labels: Fix, 나연

#319 Feat/#317 coach mark
  src/@components/@common/Modal/index.tsx
  src/@components/@common/Modal/style.ts
  src/@components/CardCollectionPage/CoachMark/index.tsx
  src/@components/CardCollectionPage/CoachMark/style.ts
  src/@components/CardCollectionPage/hooks/useCoachMark.ts
  src/@components/CardCollectionPage/index.tsx
  src/style/theme.ts
Labels: Feature, 나연

#321 Feat/#315 card blacklist
  src/@components/@common/Toast/ToastProvider.tsx
  src/@components/@common/Toast/context.ts
  src/@components/@common/Toast/hooks/useTimeout.ts
  src/@components/@common/Toast/hooks/useToast.ts
  src/@components/@common/Toast/style.ts
  src/@components/@common/hooks/useShowByQuery.ts
  src/@components/CardCollectionPage/Card/MenuModal/index.tsx
  src/@components/CardCollectionPage/Card/MenuModal/style.ts
  src/@components/CardCollectionPage/Card/index.tsx
  src/@components/CardCollectionPage/Card/style.ts
  src/@components/CardCollectionPage/CardSlider/index.tsx
  src/@components/CardCollectionPage/hooks/useBlacklist.ts
  src/@components/CardCollectionPage/hooks/useCardLists.ts
  src/@components/CardCollectionPage/hooks/useCardSwiper.ts
  src/@components/CardCollectionPage/index.tsx
  src/core/api/cardCollection.ts
  src/core/api/common/axios.ts
  src/core/api/common/constants.ts
Labels: Feature, 은형

#316 Feat/#309 last card
  src/@components/@common/hooks/useShowByQuery.ts
  src/@components/CardCollectionPage/Card/LastCard/index.tsx
  src/@components/CardCollectionPage/Card/LastCard/style.ts
  src/@components/CardCollectionPage/CardSlider/index.tsx
  src/@components/CardCollectionPage/CardSlider/style.ts
  src/@components/OAuthPage/OAuthKakaoPage/index.tsx
  src/@components/OAuthPage/OAuthNaverPage/index.tsx
  src/asset/icon/congratPiickle.svg
  src/asset/icon/index.ts
  src/core/atom/slider.ts
  src/util/cardCollection/filterTypeConverter.ts
  src/util/const/externalLinks.ts
Labels: Feature, 나연

#324 Fix/#322 login modal
  src/@components/@common/LoginModal/index.tsx
  src/@components/@common/LoginModal/style.ts
  src/@components/BestPiicklePage/BestPiickleRank/RankItem/index.tsx
  src/@components/BestPiicklePage/BestPiickleRank/index.tsx
  src/@components/CardCollectionPage/Card/CardMenu/index.tsx
  src/@components/CardCollectionPage/Card/index.tsx
  src/@components/CardCollectionPage/CardSlider/index.tsx
  src/@components/CardCollectionPage/index.tsx
  src/@components/MainPage/Banner/index.tsx
  src/@components/MainPage/Banner/style.ts
Labels: Refactor, 은형

#327 Feat/#326 vote credential
  src/@components/MainPage/hooks/useBallotLists.ts
  src/@components/VotePage/VoteContent/BeforeVoteList/index.tsx
  src/@components/VotePage/hooks/useBallotTopic.ts
  src/core/api/common/axios.ts
  src/core/api/vote.ts
Labels: Feature, 나연

#328 Feat/#323 gtm
  src/@components/@common/BestPiickleCard/LastBestPiickleCard/index.tsx
  src/@components/@common/BestPiickleCard/index.tsx
  src/@components/@common/HeadingTitleContainer/index.tsx
  src/@components/@common/Toast/ToastProvider.tsx
  src/@components/BestPiicklePage/BestPiickleRank/RankItem/index.tsx
  src/@components/BestPiicklePage/BestPiickleRank/index.tsx
  src/@components/BestPiicklePage/BestPiickleRecommend/RecommendItem/index.tsx
  src/@components/BestPiicklePage/BestPiickleRecommend/index.tsx
  src/@components/CardCollectionPage/Card/CardMenu/index.tsx
  src/@components/CardCollectionPage/Card/LastCard/index.tsx
  src/@components/CardCollectionPage/Card/MenuModal/index.tsx
  src/@components/CardCollectionPage/Card/index.tsx
  src/@components/CardCollectionPage/CardSlider/index.tsx
  src/@components/MainPage/Banner/Slide/index.tsx
  src/@components/MainPage/Banner/SlideContent/index.tsx
  src/@components/MainPage/Banner/index.tsx
  src/@components/MainPage/BestPiickle/index.tsx
  src/@components/MainPage/MoodPiickle/index.tsx
  src/@components/MainPage/StripBanner/index.tsx
  src/@components/MainPage/TopicLink/index.tsx
  src/asset/icon/IcBookmarkCheck_16_20.tsx
  src/asset/icon/IcBookmarkCheck_23_28.tsx
  src/asset/icon/IcMenuBtn.tsx
  src/asset/icon/IcShareBtn.tsx
  src/asset/icon/socialLoginLogos.svg
  src/util/const/gtm.ts
  src/util/main/banner.ts
Labels: Feature, 나연

#331 Feat/#330 event banner
  src/@components/MainPage/StripBanner/index.tsx
  src/@components/MainPage/StripBanner/style.ts
  src/asset/image/eventStripBanner.webp
  src/asset/image/index.tsx
  src/asset/image/origin/eventStripBanner.png
  src/asset/image/origin/index.tsx
  src/util/const/gtm.ts
Labels: Feature, 나연

#329 Feat/#325 event product
  src/@components/@common/Header/EventHeader/index.tsx
  src/@components/@common/Header/EventHeader/style.ts
  src/@components/@common/Modal/index.tsx
  src/@components/@common/Modal/style.ts
  src/@components/@common/Toast/ToastProvider.tsx
  src/@components/@common/Toast/style.ts
  src/@components/@common/hooks/useCardType.ts
  src/@components/@common/hooks/useDraggableYContainer.ts
  src/@components/@common/hooks/useDrawer.ts
  src/@components/CardCollectionPage/Card/CardMenu/index.tsx
  src/@components/CardCollectionPage/Card/CardMenu/style.ts
  src/@components/CardCollectionPage/Card/CommentModal/index.tsx
  src/@components/CardCollectionPage/Card/CommentModal/style.ts
  src/@components/CardCollectionPage/Card/EventCard/index.tsx
  src/@components/CardCollectionPage/Card/EventCard/style.ts
  src/@components/CardCollectionPage/Card/index.tsx
  src/@components/CardCollectionPage/CardSlider/index.tsx
  src/@components/CardCollectionPage/hooks/useCardLists.ts
  src/@components/CardCollectionPage/hooks/useComments.ts
  src/@components/CardCollectionPage/hooks/useParticipantCount.ts
  src/@components/CardCollectionPage/index.tsx
  src/@components/CardCollectionPage/style.ts
  src/@components/EventPage/index.tsx
  src/@components/EventPage/style.ts
  src/Router.tsx
  src/asset/icon/IcCommentBtn.tsx
  src/asset/icon/IcSubmitBtn.tsx
  src/asset/icon/eventArrow.svg
  src/asset/icon/index.ts
  src/core/api/cardCollection.ts
  src/core/atom/event.ts
  src/core/routes/path.ts
  src/style/theme.ts
  src/types/cardCollection.ts
Labels: Feature, 은형

#332 Feat/#322 qa
  src/@components/@common/BestPiickleCard/LastBestPiickleCard/index.tsx
  src/@components/@common/BestPiickleCard/index.tsx
  src/@components/@common/Toast/ToastProvider.tsx
  src/@components/@common/hooks/useStorageModal.ts
  src/@components/BestPiicklePage/BestPiickleRecommend/index.tsx
  src/@components/CardCollectionPage/hooks/useCoachMark.ts
  src/@components/CardCollectionPage/index.tsx
  src/@components/MainPage/BestPiickle/index.tsx
  src/@components/MainPage/UpdateModal/index.tsx
  src/@components/MainPage/UpdateModal/style.ts
  src/@components/MainPage/hooks/useUpdateModal.ts
  src/@components/MainPage/index.tsx
  src/util/main/versionUpdateList.ts
Labels: Feature, Fix, 나연
