Repository TeamPiickle/client, pull requests merged in 2023-05, with the labels that each got.

#278 Feat/#277 update
  src/@components/@common/Header/HeaderMinVer/index.tsx
  src/@components/@common/Modal/index.tsx
  src/@components/CardCollectionPage/FilterModal/@hooks/useFilterTags.ts
  src/@components/MainPage/UpdateModal/index.tsx
  src/@components/MainPage/UpdateModal/style.ts
  src/@components/MainPage/hooks/useUpdateModal.ts
  src/@components/MainPage/index.tsx
  src/util/main/versionUpdateList.ts
Labels: Feature, 나연

#281 #277 업데이트 알림 뷰
  src/@components/@common/Modal/index.tsx
  src/@components/MainPage/UpdateModal/index.tsx
  src/@components/MainPage/hooks/useUpdateModal.ts
  src/@components/MainPage/index.tsx
  src/util/main/versionUpdateList.ts
Labels: Refactor, 주함

#283 [ feat ] withCredentials 옵션 설정
  src/core/api/common/axios.ts
Labels: Feature, 나연

#284 Feat/#269 qa
  src/@components/@common/CTABtn/HeadlessCTAButton.tsx
  src/@components/@common/CTABtn/index.tsx
  src/@components/@common/CTABtn/style.ts
  src/@components/@common/Header/HeaderMinVer/style.ts
  src/@components/@common/Header/index.tsx
  src/@components/@common/Header/style.ts
  src/@components/@common/LoginModal/style.ts
  src/@components/@common/Modal/style.ts
  src/@components/@common/hooks/useScrollPosition.ts
  src/@components/CardCollectionPage/Card/index.tsx
  src/@components/CardCollectionPage/Card/style.ts
  src/@components/CardCollectionPage/CardSlider/index.tsx
  src/@components/CardCollectionPage/CardSlider/style.ts
  src/@components/CardCollectionPage/hooks/useHeaderChange.ts
  src/@components/CardCollectionPage/index.tsx
  src/@components/CardCollectionPage/style.ts
  src/@components/MainPage/CTABtn/style.ts
  src/@components/MainPage/Medley/MedleyPreview/index.tsx
  src/@components/MainPage/Medley/MedleyPreview/style.ts
  src/@components/MainPage/Medley/index.tsx
  src/@components/MainPage/Medley/style.ts
  src/@components/MainPage/UpdateModal/index.tsx
  src/@components/MainPage/UpdateModal/style.ts
  src/@components/MainPage/hooks/useUpdateModal.ts
  src/@components/MainPage/index.tsx
  src/asset/image/index.tsx
  src/asset/image/medleyBanner.webp
  src/asset/image/origin/index.tsx
  src/asset/image/origin/medleyBanner.png
Labels: Feature, 주함

#285 Bug/#269 qa
  src/@components/@common/LoginModal/style.ts
  src/@components/@common/hooks/useScrollPosition.ts
  src/@components/@common/hooks/useScrollToTop.ts
  src/@components/CardCollectionPage/Card/index.tsx
  src/@components/CardCollectionPage/CardSlider/index.tsx
  src/@components/CardCollectionPage/CardSlider/style.ts
  src/@components/CardCollectionPage/hooks/useCardSwiper.ts
  src/@components/CardCollectionPage/hooks/useHeaderChange.ts
  src/@components/CardCollectionPage/index.tsx
  src/@components/CategoryPage/CategoryContents/style.ts
  src/@components/CategoryPage/index.tsx
  src/@components/CategoryPage/style.ts
  src/@components/JoinPage/AgreePage/index.tsx
  src/@components/JoinPage/UserProfilePage/index.tsx
  src/@components/LoginPage/index.tsx
  src/@components/MainPage/UpdateModal/index.tsx
  src/@components/MainPage/hooks/useUpdateModal.ts
  src/@components/MyPage/index.tsx
  src/@components/VotePage/VoteContent/BeforeVoteList/index.tsx
  src/core/atom/slider.ts
Labels: Feature, Refactor, Fix, 나연

#289 Card Memoization
  .gitignore
  src/@components/CardCollectionPage/Card/LastCard/index.tsx
Labels: Feature, 주함
