Repository TeamPiickle/client, pull requests merged in 2023-07, with the labels that each got.

#301 Feat/#300 best piickle
  src/@components/@common/BestPiickleCard/index.tsx
  src/@components/@common/BestPiickleCard/style.ts
  src/@components/@common/HeadingTitleContainer/index.tsx
  src/@components/@common/HeadingTitleContainer/style.ts
  src/@components/@common/hooks/useDraggingContainer.ts
  src/@components/BestPiicklePage/BestPiickleRank/RankItem/index.tsx
  src/@components/BestPiicklePage/BestPiickleRank/RankItem/style.ts
  src/@components/BestPiicklePage/BestPiickleRank/index.tsx
  src/@components/BestPiicklePage/BestPiickleRank/style.ts
  src/@components/BestPiicklePage/BestPiickleRecommend/RecommendItem/index.tsx
  src/@components/BestPiicklePage/BestPiickleRecommend/RecommendItem/style.ts
  src/@components/BestPiicklePage/BestPiickleRecommend/index.tsx
  src/@components/BestPiicklePage/BestPiickleRecommend/style.ts
  src/@components/BestPiicklePage/index.tsx
  src/@components/BestPiicklePage/style.ts
  src/@components/MainPage/BestPiickle/BestPiickleCard/index.tsx
  src/@components/MainPage/BestPiickle/BestPiickleCard/style.ts
  src/@components/MainPage/BestPiickle/index.tsx
  src/@components/MainPage/Medley/index.tsx
  src/@components/MainPage/MoodPiickle/index.tsx
  src/@components/MainPage/PiickleMe/index.tsx
  src/@components/index.ts
  src/Router.tsx
  src/core/routes/path.ts
  src/style/theme.ts
  src/util/category/categoryList.ts
  src/util/main/headingTitles.ts
Labels: Feature, 은형

#304 Feat/#301 best piickle API
  src/@components/@common/BestPiickleCard/LastBestPiickleCard/index.tsx
  src/@components/@common/BestPiickleCard/LastBestPiickleCard/style.ts
  src/@components/@common/BestPiickleCard/index.tsx
  src/@components/@common/BestPiickleCard/style.ts
  src/@components/@common/hooks/useNavigateCardCollection.ts
  src/@components/BestPiicklePage/BestPiickleRank/RankItem/index.tsx
  src/@components/BestPiicklePage/BestPiickleRank/RankItem/style.ts
  src/@components/BestPiicklePage/BestPiickleRank/index.tsx
  src/@components/BestPiicklePage/BestPiickleRecommend/RecommendItem/index.tsx
  src/@components/BestPiicklePage/BestPiickleRecommend/hooks/useCardsByGender.ts
  src/@components/BestPiicklePage/BestPiickleRecommend/hooks/useRecentlyBookmarked.ts
  src/@components/BestPiicklePage/BestPiickleRecommend/index.tsx
  src/@components/BestPiicklePage/index.tsx
  src/@components/BestPiicklePage/style.ts
  src/@components/CardCollectionPage/hooks/useCardLists.ts
  src/@components/MainPage/BestPiickle/index.tsx
  src/core/api/common/constants.ts
  src/types/cardCollection.ts
Labels: Feature, 은형

#299 Feat/#133 social login 2
  package.json
  src/@components/@common/Header/index.tsx
  src/@components/@common/Header/style.ts
  src/@components/@common/MenuBar/index.tsx
  src/@components/JoinPage/AgreePage/index.tsx
  src/@components/JoinPage/UserProfilePage/index.tsx
  src/@components/LoginPage/SocialLogin/index.tsx
  src/@components/LoginPage/SocialLoginBtn/index.tsx
  src/@components/LoginPage/SocialLoginBtn/style.ts
  src/@components/MainPage/StripBanner/index.tsx
  src/@components/MainPage/StripBanner/style.ts
  src/@components/MainPage/index.tsx
  src/@components/OAuthPage/OAuthKakaoPage/index.tsx
  src/@components/OAuthPage/OAuthNaverPage/index.tsx
  src/@components/OAuthPage/SuccessPage/index.tsx
  src/@components/OAuthPage/SuccessPage/style.ts
  src/asset/icon/index.ts
  src/asset/icon/socialLoginLogos.svg
  src/asset/image/origin/stripBanner.png
  src/asset/image/stripBanner.webp
  src/core/api/common/constants.ts
  src/core/api/login.ts
  src/core/hooks/useAuth.ts
  src/style/theme.ts
  src/util/login/oauth.ts
Labels: Feature, Fix, 나연

#294 Feat/#133 social login
  package.json
  src/@components/@common/Header/index.tsx
  src/@components/@common/Header/style.ts
  src/@components/@common/MenuBar/index.tsx
  src/@components/JoinPage/AgreePage/index.tsx
  src/@components/LoginPage/LoginForm/style.ts
  src/@components/LoginPage/SocialLogin/index.tsx
  src/@components/LoginPage/SocialLogin/style.ts
  src/@components/LoginPage/SocialLoginBtn/index.tsx
  src/@components/LoginPage/SocialLoginBtn/style.ts
  src/@components/LoginPage/index.tsx
  src/@components/MainPage/StripBanner/index.tsx
  src/@components/MainPage/StripBanner/style.ts
  src/@components/MainPage/index.tsx
  src/@components/OAuthPage/OAuthKakaoPage/index.tsx
  src/@components/OAuthPage/OAuthNaverPage/index.tsx
  src/@components/OAuthPage/SuccessPage/index.tsx
  src/@components/OAuthPage/SuccessPage/style.ts
  src/@components/index.ts
  src/Router.tsx
  src/asset/icon/index.ts
  src/asset/icon/kakaoLogo.svg
  src/asset/icon/leftSpeechBubble.svg
  src/asset/icon/naverLogo.svg
  src/asset/icon/rightSpeechBubble.svg
  src/asset/icon/socialLoginLogos.svg
  src/asset/image/origin/stripBanner.png
  src/asset/image/stripBanner.webp
  src/core/api/common/constants.ts
  src/core/api/login.ts
  src/core/hooks/useAuth.ts
  src/core/routes/path.ts
  src/env.d.ts
  src/style/theme.ts
  src/util/login/oauth.ts
Labels: Feature, 나연

#308 Fix/#307 HeadingTitle 에러
  src/@components/BookmarkPage/index.tsx
Labels: Fix, 은형
